function txt2trialxml(inputTxtFile, outputXmlFile, treeID, mainTreeID)
% TXT2TRIALXML  Convert a trial-mission definition text file into a
%               BehaviorTree.CPP XML file matching the Trial_Mission_File
%               format (DriveToWorldWaypoint / DurationTrick nodes).

    if nargin < 3 || isempty(treeID)
        [~, treeID, ~] = fileparts(inputTxtFile);
    end

    rows = readMissionRows(inputTxtFile);

    nodeLines = {};
    typesUsed = containers.Map('KeyType', 'char', 'ValueType', 'logical');

    for i = 1:numel(rows)
        r = rows(i);

        if ~strcmpi(r.trick_identifier, 'no_trick')
            % --- DurationTrick node ---
            typesUsed('DurationTrick') = true;
            nodeLines{end+1} = formatDurationTrick(r, i); %#ok<AGROW>

        elseif ~strcmpi(r.object_identifier, 'n/a')
            % --- DriveToObjectWaypoint node (object tracking) ---
            typesUsed('DriveToObjectWaypoint') = true;
            nodeLines{end+1} = formatDriveToObjectWaypoint(r, i); %#ok<AGROW>

        else
            % --- DriveToWorldWaypoint node ---
            typesUsed('DriveToWorldWaypoint') = true;
            nodeLines{end+1} = formatDriveToWorldWaypoint(r, i); %#ok<AGROW>
        end
    end

    xml = buildXmlDocument(treeID, mainTreeID, nodeLines, typesUsed);

    fid = fopen(outputXmlFile, 'w');
    if fid == -1
        error('txt2trialxml:fileOpen', 'Could not open output file: %s', outputXmlFile);
    end
    fwrite(fid, xml);
    fclose(fid);

    fprintf('Wrote %d node(s) to %s\n', numel(rows), outputXmlFile);
end


function rows = readMissionRows(inputTxtFile)
    fid = fopen(inputTxtFile, 'r');
    if fid == -1
        error('txt2trialxml:fileOpen', 'Could not open input file: %s', inputTxtFile);
    end
    cleanupObj = onCleanup(@() fclose(fid));

    rows = struct('identifier', {}, 'waypoint', {}, 'mask', {}, ...
                   'tolerance', {}, 'hold_time', {}, 'object_identifier', {}, ...
                   'confidence', {}, 'trick_identifier', {}, 'timeout', {});

    lineNum = 0;
    while true
        line = fgetl(fid);
        if ~ischar(line)
            break;
        end
        lineNum = lineNum + 1;

        trimmed = strtrim(line);
        if isempty(trimmed)
            continue;
        end
        if startsWith(trimmed, '%') || startsWith(trimmed, '#')
            continue;
        end
        if startsWith(lower(trimmed), 'identifier')
            continue; % header row
        end

        fields = strsplit(trimmed, ',');
        fields = strtrim(fields);

        if numel(fields) < 9
            warning('txt2trialxml:badRow', ...
                'Line %d has %d fields (expected 9). Skipping: %s', ...
                lineNum, numel(fields), trimmed);
            continue;
        end

        r.identifier         = fields{1};
        r.waypoint            = parseVector(fields{2});
        r.mask                 = parseVector(fields{3});
        r.tolerance             = parseVector(fields{4});
        r.hold_time              = str2double(fields{5});
        r.object_identifier       = fields{6};
        r.confidence               = str2double(fields{7});
        r.trick_identifier          = fields{8};
        r.timeout                    = str2double(fields{9});

        rows(end+1) = r; %#ok<AGROW>
    end
end


function v = parseVector(tok)
    % Strip brackets and parse a space-separated 6-element vector.
    tok = strtrim(tok);
    tok = strrep(tok, '[', '');
    tok = strrep(tok, ']', '');
    v = sscanf(tok, '%f')';
    if numel(v) ~= 6
        error('txt2trialxml:badVector', ...
            'Expected a 6-element vector, got "%s"', tok);
    end
end


function s = vec2str(v)
    % Format a 6-element numeric vector as comma-separated, matching the
    % style of the reference file (e.g. "0.2,0.2,0.2,0.1,0.1,0.1").
    parts = arrayfun(@(x) strtrim(sprintf('%g', x)), v, 'UniformOutput', false);
    s = strjoin(parts, ',');
end


function s = numstr(x)
    s = strtrim(sprintf('%g', x));
end


function line = formatDriveToWorldWaypoint(r, idx)
    line = sprintf([ ...
        '      <DriveToWorldWaypoint world_waypoint="%s"\n' ...
        '                            waypoint_mask="%s"\n' ...
        '                            tolerance="%s"\n' ...
        '                            hold_time="%s"\n' ...
        '                            timeout="%s"\n' ...
        '                            _description="%s"/>'], ...
        vec2str(r.waypoint), vec2str(r.mask), vec2str(r.tolerance), ...
        numstr(r.hold_time), numstr(r.timeout), ...
        sprintf('Leg %d: %s', idx, r.identifier));
end


function line = formatDurationTrick(r, idx)
    line = sprintf([ ...
        '      <DurationTrick trick="%s"\n' ...
        '                            waypoint_mask="%s"\n' ...
        '                            tolerance="%s"\n' ...
        '                            hold_time="%s"\n' ...
        '                            duration="%s"\n' ...
        '                            timeout="%s"\n' ...
        '                            _description="%s"/>'], ...
        r.trick_identifier, vec2str(r.mask), vec2str(r.tolerance), ...
        numstr(r.hold_time), numstr(r.hold_time), numstr(r.timeout), ...
        sprintf('Leg %d: %s', idx, r.trick_identifier));
end


function line = formatDriveToObjectWaypoint(r, idx)
    line = sprintf([ ...
        '      <DriveToObjectWaypoint tracking_position="%s"\n' ...
        '                            waypoint_mask="%s"\n' ...
        '                            tolerance="%s"\n' ...
        '                            hold_time="%s"\n' ...
        '                            object_identifier="%s"\n' ...
        '                            confidence="%s"\n' ...
        '                            timeout="%s"\n' ...
        '                            _description="%s"/>'], ...
        vec2str(r.waypoint), vec2str(r.mask), vec2str(r.tolerance), ...
        numstr(r.hold_time), r.object_identifier, numstr(r.confidence), ...
        numstr(r.timeout), sprintf('Leg %d: track %s', idx, r.object_identifier));
end


function xml = buildXmlDocument(treeID, mainTreeID, nodeLines, typesUsed)
    header = sprintf([ ...
        '<?xml version="1.0" encoding="UTF-8"?>\n' ...
        '<root BTCPP_format="4"\n' ...
        '      main_tree_to_execute="%s">\n' ...
        '  <BehaviorTree ID="%s">\n' ...
        '    <Sequence>\n'], mainTreeID, treeID);

    body = strjoin(nodeLines, '\n');

    footer = sprintf([ ...
        '\n    </Sequence>\n' ...
        '  </BehaviorTree>\n\n' ...
        '  <!-- Description of Node Models (used by Groot) -->\n' ...
        '  <TreeNodesModel>\n%s' ...
        '  </TreeNodesModel>\n\n' ...
        '</root>\n'], buildNodeModels(typesUsed));

    xml = [header, body, footer];
end


function s = buildNodeModels(typesUsed)
    s = '';
    if isKey(typesUsed, 'DriveToWorldWaypoint')
        s = [s, sprintf([ ...
            '    <Action ID="DriveToWorldWaypoint">\n' ...
            '      <input_port name="world_waypoint" type="std::vector<float>">[6x1] Target position and orientation in world frame</input_port>\n' ...
            '      <input_port name="waypoint_mask" type="std::vector<bool>">[6x1] Specifies which states the controller must prioritize</input_port>\n' ...
            '      <input_port name="tolerance" type="std::vector<float>">[6x1] Allowed error margin for arrival</input_port>\n' ...
            '      <input_port name="hold_time" type="float">Time to remain within tolerance before returning SUCCESS</input_port>\n' ...
            '      <input_port name="timeout" type="float">Time to attempt the task before giving up and returning FAILURE</input_port>\n' ...
            '    </Action>\n'])];
    end
    if isKey(typesUsed, 'DurationTrick')
        s = [s, sprintf([ ...
            '    <Action ID="DurationTrick">\n' ...
            '      <input_port name="trick" type="std::string">Identifier of the trick maneuver to execute</input_port>\n' ...
            '      <input_port name="waypoint_mask" type="std::vector<bool>">[6x1] Specifies which states the controller must prioritize</input_port>\n' ...
            '      <input_port name="tolerance" type="std::vector<float>">[6x1] Allowed error margin</input_port>\n' ...
            '      <input_port name="hold_time" type="float">Time to hold before considering the trick complete</input_port>\n' ...
            '      <input_port name="duration" type="float">Duration the trick maneuver is actively executed</input_port>\n' ...
            '      <input_port name="timeout" type="float">Time to attempt the task before giving up and returning FAILURE</input_port>\n' ...
            '    </Action>\n'])];
    end
    if isKey(typesUsed, 'DriveToObjectWaypoint')
        s = [s, sprintf([ ...
            '    <Action ID="DriveToObjectWaypoint">\n' ...
            '      <input_port name="tracking_position" type="std::vector<float>">[6x1] Target position/orientation relative to the tracked object</input_port>\n' ...
            '      <input_port name="waypoint_mask" type="std::vector<bool>">[6x1] Specifies which states the controller must prioritize</input_port>\n' ...
            '      <input_port name="tolerance" type="std::vector<float>">[6x1] Allowed error margin for arrival</input_port>\n' ...
            '      <input_port name="hold_time" type="float">Time to remain within tolerance before returning SUCCESS</input_port>\n' ...
            '      <input_port name="object_identifier" type="std::string">Identifier of the object being tracked</input_port>\n' ...
            '      <input_port name="confidence" type="float">Minimum detection confidence required</input_port>\n' ...
            '      <input_port name="timeout" type="float">Time to attempt the task before giving up and returning FAILURE</input_port>\n' ...
            '    </Action>\n'])];
    end
end