function clearAutogeneratedFiles()
%{
This is a housekeeping function to delete all folders in
SimulinkPlant/codegen/slprj_and_caches.

%}
%add prj_path_list if it doesn't already exist in this scope
if(~exist("prj_path_list","var"))
    prj_path_list = getProjectPaths();
end

condemned_contents = dir(prj_path_list.cache_path);
condemned_contents = condemned_contents(~ismember({condemned_contents.name},{'.','..'}));

if(numel(condemned_contents)>0)
    for k = 1:numel(condemned_contents)
        item_path = fullfile(condemned_contents.folder,condemned_contents(k).name);
        if condemned_contents(k).isdir
            rmdir(item_path,'s');
        else
            delete(item_path);
        end
    end
end

fprintf("Cleared out anything autogenerated temporary scripts.\n");
end