%{
This script is run whenever the project closes to clean up unneeded files.
%}
%load the file paths if the variable doesn't already exist
if(~exist("prj_path_list","var"))
    prj_path_list = getProjectPaths();
end

%clears src/temp directory
clearTemp();

%clears out the cache and slprjs dumped in the codegen folder
clearAutogeneratedFiles();


fprintf("Goodbye.\n")