function missionfile_FF_v0 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  MISSIONFILE_FF_V0 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  MISSIONFILE_FF_V0 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  MISSIONFILE_FF_V0 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  missionfile_FF_v0 = importfile("C:\GitHub\Cyclone Robosub\SimulinkPlant\src\inits\missionfile_FF_v0.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Oct-2025 18:37:35

%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
lastRowOfDataIdx = 0;
if nargin <= 2
    dataLines = [2, Inf];
    lastRowOfDataIdx = 1;
elseif dataLines(end,2) >= Inf
    lastRowOfDataIdx = size(dataLines, 1);
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
if lastRowOfDataIdx == 1
    opts.DataRange = "A" + dataLines(1, 1);
else
    opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);
end

% Specify column names and types
opts.VariableNames = ["Maneuver", "Duration", "Parameter"];
opts.VariableTypes = ["string", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Maneuver", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Maneuver", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Duration", "Parameter"], "FillValue", 0);

% Import the data
missionfile_FF_v0 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    if idx == lastRowOfDataIdx
        opts.DataRange = "A" + dataLines(idx, 1);
    else
        opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    end
    tb = readtable(workbookFile, opts, "UseExcel", false);
    missionfile_FF_v0 = [missionfile_FF_v0; tb]; %#ok<AGROW>
end

end