function drive_in_a_square_feedforward_missionfile = importMissionFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DRIVE_IN_A_SQUARE_FEEDFORWARD_MISSIONFILE = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as a table.
%
%  DRIVE_IN_A_SQUARE_FEEDFORWARD_MISSIONFILE = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  drive_in_a_square_feedforward_missionfile = importfile("C:\GitHub\Cyclone Robosub\SimulinkPlant\utils\drive_in_a_square_feedforward_missionfile.txt", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Oct-2025 19:47:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["command_type", "var1", "var2", "var3", "var4", "var5", "var6", "var7", "var8", "var9"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "error";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "command_type", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "command_type", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["var1", "var2", "var3", "var4", "var5", "var6", "var7", "var8", "var9"], "FillValue", 0);
opts = setvaropts(opts, ["var1", "var2", "var3", "var4", "var5", "var6", "var7", "var8", "var9"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["var1", "var2", "var3", "var4", "var5", "var6", "var7", "var8", "var9"], "ThousandsSeparator", ",");

% Import the data
drive_in_a_square_feedforward_missionfile = readtable(filename, opts);

end